name: OWASP Dependency Check (Juice Shop)

on:
  workflow_dispatch:
  push:
  pull_request:
  create:
  delete:
  release:
  issues:
  issue_comment:
  schedule:
    - cron: "0 3 * * *"

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Baixar última versão do Dependency Check
        run: |
          curl -s https://api.github.com/repos/dependency-check/DependencyCheck/releases/latest \
          | grep "browser_download_url.*zip" \
          | cut -d '"' -f 4 \
          | wget -qi -

          unzip dependency-check-*.zip
          mv dependency-check /opt/dependency-check

      - name: Executar scan (Node / Juice Shop)
        run: |
          /opt/dependency-check/bin/dependency-check.sh \
            --project "Juice-Shop-Fork" \
            --scan package.json \
            --scan package-lock.json \
            --format ALL \
            --out dependency-check-report \
            --enableExperimental \
            --enableRetired

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
